"use client";

/**
 * TidePoolRitual — 潮音池
 * Pilot gimmick for the Sacred Realms concept (see CLAUDE.md 🔮 Future
 * Vision). Only wired up for 汐見潮 (Ushio) today, as a small standalone
 * overlay separate from the core omikuji draw flow — type a worry, watch
 * it dissolve into the water, receive one short, comforting line.
 *
 * The reply is now generated by /api/tide-pool (a focused, single-turn
 * prompt distinct from Ushio's full omikuji-reading persona). The text
 * dissolve animation always plays for at least DISSOLVE_MS so it never
 * feels rushed; if the model call takes longer, a soft pulsing indicator
 * fills the gap. The static FALLBACK_RESPONSES only fire if the request
 * fails outright.
 */

import { useCallback, useState } from "react";
import { motion, AnimatePresence } from "motion/react";

type Phase = "input" | "dissolving" | "response";

const DISSOLVE_MS = 1500;

const FALLBACK_RESPONSES = [
  "丟掉的，就讓它留在水裡吧。你不用再帶著走了。",
  "浪退了，事情就過去了。放輕鬆，順著水走。",
  "你聽，水面已經平靜下來了——你也可以。",
];

interface TidePoolRitualProps {
  onClose: () => void;
}

export default function TidePoolRitual({ onClose }: TidePoolRitualProps) {
  const [phase, setPhase] = useState<Phase>("input");
  const [text, setText] = useState("");
  const [response, setResponse] = useState("");

  const handleRelease = useCallback(async () => {
    const worry = text.trim();
    if (worry.length < 2) return;
    setPhase("dissolving");

    const minDelay = new Promise<void>((resolve) => window.setTimeout(resolve, DISSOLVE_MS));
    const reply = fetch("/api/tide-pool", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ worry }),
    })
      .then(async (res) => {
        if (!res.ok) throw new Error("request failed");
        const data = (await res.json()) as { response?: string };
        if (!data.response) throw new Error("empty response");
        return data.response;
      })
      .catch(
        () => FALLBACK_RESPONSES[Math.floor(Math.random() * FALLBACK_RESPONSES.length)]
      );

    const [, finalReply] = await Promise.all([minDelay, reply]);
    setResponse(finalReply);
    setPhase("response");
  }, [text]);

  const handleRestart = useCallback(() => {
    setText("");
    setResponse("");
    setPhase("input");
  }, []);

  return (
    <motion.div
      className="absolute inset-0 z-30 flex flex-col items-center justify-center gap-6 px-6"
      style={{ background: "rgba(8, 14, 18, 0.88)" }}
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
    >
      <button
        onClick={onClose}
        className="absolute top-4 right-4 text-morandi-stone/45 hover:text-cream-200/70 text-xs tracking-widest transition-colors duration-200"
      >
        ✕ 離開潮音池
      </button>

      <div className="text-center">
        <p className="text-morandi-sage/55 text-xs tracking-[0.3em] uppercase mb-1">潮音池</p>
        <h2 className="font-serif text-lg text-cream-100">把心裡的煩惱，交給水吧</h2>
      </div>

      <AnimatePresence mode="wait">
        {phase === "input" && (
          <motion.div
            key="input"
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.4 }}
            className="w-full max-w-sm flex flex-col gap-3"
          >
            <textarea
              value={text}
              onChange={(e) => setText(e.target.value)}
              placeholder="寫下一件讓你煩心的事……"
              rows={3}
              maxLength={150}
              className="w-full rounded-2xl border border-morandi-sage/25 bg-black/20 text-cream-100 placeholder-morandi-stone/40 text-sm p-4 resize-none focus:outline-none focus:border-morandi-sage/50 transition-colors leading-relaxed"
            />
            <motion.button
              onClick={handleRelease}
              disabled={text.trim().length < 2}
              whileHover={text.trim().length >= 2 ? { scale: 1.03 } : {}}
              whileTap={text.trim().length >= 2 ? { scale: 0.97 } : {}}
              className="px-6 py-2.5 rounded-full border border-morandi-sage/40 bg-morandi-sage/10 text-cream-100 text-sm tracking-widest hover:bg-morandi-sage/20 transition-colors duration-300 disabled:opacity-40"
            >
              🌊 讓它順著水走
            </motion.button>
          </motion.div>
        )}

        {phase === "dissolving" && (
          <motion.div
            key="dissolving"
            className="w-full max-w-sm text-center flex flex-col items-center gap-5"
          >
            <motion.p
              className="text-cream-200/80 text-sm leading-relaxed"
              initial={{ opacity: 1, filter: "blur(0px)", y: 0 }}
              animate={{ opacity: 0, filter: "blur(6px)", y: 18 }}
              transition={{ duration: 1.4, ease: [0.4, 0, 0.6, 1] }}
            >
              {text}
            </motion.p>
            {/* soft pulse that only becomes visible once the text has
                mostly faded — fills any gap if the model call outlasts
                the dissolve animation itself */}
            <motion.div
              className="flex gap-1.5"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 1.2, duration: 0.5 }}
            >
              {[0, 1, 2].map((i) => (
                <motion.span
                  key={i}
                  className="w-1.5 h-1.5 rounded-full bg-morandi-sage/60"
                  animate={{ opacity: [0.25, 1, 0.25] }}
                  transition={{ duration: 1.3, repeat: Infinity, delay: i * 0.2, ease: "easeInOut" }}
                />
              ))}
            </motion.div>
          </motion.div>
        )}

        {phase === "response" && (
          <motion.div
            key="response"
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
            className="w-full max-w-sm flex flex-col items-center gap-5"
          >
            <p className="text-cream-100 text-sm leading-relaxed text-center italic">
              「{response}」
            </p>
            <motion.button
              onClick={handleRestart}
              whileHover={{ scale: 1.03 }}
              whileTap={{ scale: 0.97 }}
              className="px-6 py-2.5 rounded-full border border-morandi-sage/30 text-morandi-stone/60 text-xs tracking-widest hover:border-morandi-sage/55 hover:text-cream-200 transition-colors duration-300"
            >
              再放下一件事
            </motion.button>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}
